### ISSUE TITLE
M_PI not defined

### ISSUE THREAD

**Issue by spkadam** [agarie/vector-field-histogram#10]
make
gcc -Iinclude -Wall -O3 -std=c99 -c src/histogram_grid.c -o histogram_grid.o
src/histogram_grid.c: In function ‘grid_update’:
src/histogram_grid.c:56:64: error: ‘M_PI’ undeclared (first use in this function); did you mean ‘__P’?
   int new_x = pos_x + (int) floor(cells * cos(data.direction * M_PI / 180));
                                                                ^~~~
                                                                __P
src/histogram_grid.c:56:64: note: each undeclared identifier is reported only once for each function it appears in
Makefile:12: recipe for target 'histogram_grid.o' failed
make: *** [histogram_grid.o] Error 1

**Comment by agarie** [comment]
Hi @spkadam, thanks for reporting this bug. I haven't been taking care of this codebase as I should... :)

I believe I fixed this issue with f2fe008.
